name: Build and publish dev release Docker image to Github Container Registry ghcr.io and publish dev release jar to sonatype

on: workflow_dispatch

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Sonatype,Docker'
      devRelease: true
      createTag: true
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}